apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dreambook-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: api_deploymentpod
  template:
    metadata:
      labels:
        app: api_deploymentpod
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: dreambookcontainer
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dreambook-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: api_deploymentpod

