apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dreambook-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: api_deploymentpod
  template:
    metadata:
      labels:
        app: api_deploymentpod
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: dreambookcontainer
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dreambook-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: api_deploymentpod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: {{ include "dreambook-helm.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "dreambook-helm.fullname" . }}
            port:
              number: 80
        path: /api
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.host }}

