apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dreambook-argo-application
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: ArgoCD
spec:
  project: default
  source:
    repoURL: https://github.com/komdil/ArgoCDTest.git
    targetRevision: HEAD
    path: dev/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: dilshod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - Prune=true
      - SelfHeal=true
