apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: 'argocdUrl: "https://20.204.207.96"'
  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      send: [app-deploy-succeeded, app-deploy-succeeded-teams]
  service.teams: |
    recipientUrls: 
      ArgoCD: https://mrasbs.webhook.office.com/webhookb2/ac8035ee-cb56-44fa-b129-e453d02ad6d7@2f941d93-4301-4de5-bba2-20344d055b9b/IncomingWebhook/efde8f3afb6c499184b46506e14ead93/c4bd6eca-7bda-4874-bf03-8b90c00180a7
  service.webhook.teams-webhook: |
    url: https://mrasbs.webhook.office.com/webhookb2/ac8035ee-cb56-44fa-b129-e453d02ad6d7@2f941d93-4301-4de5-bba2-20344d055b9b/IncomingWebhook/efde8f3afb6c499184b46506e14ead93/c4bd6eca-7bda-4874-bf03-8b90c00180a7
    headers: 
    - name: Content-Type
      value: application/json
  template.app-deploy-succeeded: |
    webhook:
      teams-webhook:
        method: POST
        body: |
          {
            "@type": "MessageCard",
            "title": "Test Message from the ArgoCD",
            "text": "This is a test message."
          }
  template.app-deploy-succeeded-teams: |
    email:
    subject: New version of an application {{.app.metadata.name}} is up and running.
    message: |
      Application {{.app.metadata.name}} is now running new version of deployments manifests.
    teams:
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{.app.status.sync.status}}"
        },
        {
          "name": "Repository",
          "value": "{{.app.spec.source.repoURL}}"
        },
        {
          "name": "Revision",
          "value": "{{.app.status.sync.revision}}"
        }
        {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "name": "{{$c.type}}",
            "value": "{{$c.message}}",
          }
        {{end}}
        ]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Operation Application",
          "targets":[{
            "os":"default",
            "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default",
            "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
          }]
        }]
      title: New version of an application {{.app.metadata.name}} is up and running.