apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  channel-teams-url: https://mrasbs.webhook.office.com/webhookb2/ac8035ee-cb56-44fa-b129-e453d02ad6d7@2f941d93-4301-4de5-bba2-20344d055b9b/IncomingWebhook/efde8f3afb6c499184b46506e14ead93/c4bd6eca-7bda-4874-bf03-8b90c00180a7
type: Opaque