apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreambookapideployment
  namespace: dilshod
spec:
  selector:
    matchLabels:
      app: api_deploymentpod
  template:
    metadata:
      labels:
        app: api_deploymentpod
    spec:
      containers:
      - name: dreambookcontainer
        image: komdil/dreambook:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dreambookdeploymentservice
  namespace: dilshod
spec:
  selector:
    app: api_deploymentpod
  ports:
    - port: 80
      targetPort: 80
  # type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dreambook-api-ingress
  namespace: dilshod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: dilshod.20.219.235.7.nip.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: dreambookdeploymentservice
            port:
              number: 80
  tls:
  - hosts:
    - dilshod.20.219.235.7.nip.io

