apiVersion: v1
kind: Service
metadata:
  name: dreambookdeploymentservice
  namespace: dilshod
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: api_deploymentpod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreambookapideployment
  namespace: dilshod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api_deploymentpod
  template:
    metadata:
      labels:
        app: api_deploymentpod
    spec:
      containers:
      - image: komdil/dreambook:1.0.15
        imagePullPolicy: Always
        name: dreambookcontainer
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: dreambook-api-ingress
  namespace: dilshod
spec:
  rules:
  - host: dilshod.20.219.235.7.nip.io
    http:
      paths:
      - backend:
          service:
            name: dreambookdeploymentservice
            port:
              number: 80
        path: /api
        pathType: Prefix
  tls:
  - hosts:
    - dilshod.20.219.235.7.nip.io
