name: Kustomize and push
on:
  repository_dispatch:
    types: "dreambook-dev"
    #  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        default: "v1"
        required: true
jobs:
  kustomize-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
    steps:
      - name: checkout main repo
        uses: actions/checkout@v2

      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.9.2"

      - name: change manifests
        run: |
          cd ./dev
          kustomize edit set image komdil/dreambook:${{ github.event.client_payload.version }}
          cat kustomization.yaml
          kustomize build . > ./deployment/deployment.yaml

      - name: git commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          # Commit message
          commit_message: push ${{ github.event.client_payload.version }} version