name: Kustomize and push
on:
  push:
    branches: [ master ]
  # repository_dispatch:
  #   inputs:
  #     tag:
  #       description: "Tag"
  #       default: "30"
  #       required: true
jobs:
  kustomize-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main repo
        uses: actions/checkout@v2

      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.9.2"

      - name: change manifests
        run: |
          cd ./dev
          kustomize edit set image koble.azurecr.io/sample:${{ github.event.client_payload.version }}
          cat kustomization.yaml
          kustomize build . > ./deployments.yaml

      - name: git commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          # Commit message
          commit_message: push ${{ github.event.inputs.tag }} version